// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: colosseuma/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7dad3c38e43f6de, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7dad3c38e43f6de, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetCoinSymbolRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetCoinSymbolRequest) Reset()         { *m = QueryGetCoinSymbolRequest{} }
func (m *QueryGetCoinSymbolRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCoinSymbolRequest) ProtoMessage()    {}
func (*QueryGetCoinSymbolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7dad3c38e43f6de, []int{2}
}
func (m *QueryGetCoinSymbolRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCoinSymbolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCoinSymbolRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCoinSymbolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCoinSymbolRequest.Merge(m, src)
}
func (m *QueryGetCoinSymbolRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCoinSymbolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCoinSymbolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCoinSymbolRequest proto.InternalMessageInfo

func (m *QueryGetCoinSymbolRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetCoinSymbolResponse struct {
	CoinSymbol CoinSymbol `protobuf:"bytes,1,opt,name=CoinSymbol,proto3" json:"CoinSymbol"`
}

func (m *QueryGetCoinSymbolResponse) Reset()         { *m = QueryGetCoinSymbolResponse{} }
func (m *QueryGetCoinSymbolResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCoinSymbolResponse) ProtoMessage()    {}
func (*QueryGetCoinSymbolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7dad3c38e43f6de, []int{3}
}
func (m *QueryGetCoinSymbolResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCoinSymbolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCoinSymbolResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCoinSymbolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCoinSymbolResponse.Merge(m, src)
}
func (m *QueryGetCoinSymbolResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCoinSymbolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCoinSymbolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCoinSymbolResponse proto.InternalMessageInfo

func (m *QueryGetCoinSymbolResponse) GetCoinSymbol() CoinSymbol {
	if m != nil {
		return m.CoinSymbol
	}
	return CoinSymbol{}
}

type QueryAllCoinSymbolRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCoinSymbolRequest) Reset()         { *m = QueryAllCoinSymbolRequest{} }
func (m *QueryAllCoinSymbolRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllCoinSymbolRequest) ProtoMessage()    {}
func (*QueryAllCoinSymbolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7dad3c38e43f6de, []int{4}
}
func (m *QueryAllCoinSymbolRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCoinSymbolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCoinSymbolRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCoinSymbolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCoinSymbolRequest.Merge(m, src)
}
func (m *QueryAllCoinSymbolRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCoinSymbolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCoinSymbolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCoinSymbolRequest proto.InternalMessageInfo

func (m *QueryAllCoinSymbolRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllCoinSymbolResponse struct {
	CoinSymbol []CoinSymbol        `protobuf:"bytes,1,rep,name=CoinSymbol,proto3" json:"CoinSymbol"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCoinSymbolResponse) Reset()         { *m = QueryAllCoinSymbolResponse{} }
func (m *QueryAllCoinSymbolResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllCoinSymbolResponse) ProtoMessage()    {}
func (*QueryAllCoinSymbolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7dad3c38e43f6de, []int{5}
}
func (m *QueryAllCoinSymbolResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCoinSymbolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCoinSymbolResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCoinSymbolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCoinSymbolResponse.Merge(m, src)
}
func (m *QueryAllCoinSymbolResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCoinSymbolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCoinSymbolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCoinSymbolResponse proto.InternalMessageInfo

func (m *QueryAllCoinSymbolResponse) GetCoinSymbol() []CoinSymbol {
	if m != nil {
		return m.CoinSymbol
	}
	return nil
}

func (m *QueryAllCoinSymbolResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "colosseuma.colosseuma.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "colosseuma.colosseuma.QueryParamsResponse")
	proto.RegisterType((*QueryGetCoinSymbolRequest)(nil), "colosseuma.colosseuma.QueryGetCoinSymbolRequest")
	proto.RegisterType((*QueryGetCoinSymbolResponse)(nil), "colosseuma.colosseuma.QueryGetCoinSymbolResponse")
	proto.RegisterType((*QueryAllCoinSymbolRequest)(nil), "colosseuma.colosseuma.QueryAllCoinSymbolRequest")
	proto.RegisterType((*QueryAllCoinSymbolResponse)(nil), "colosseuma.colosseuma.QueryAllCoinSymbolResponse")
}

func init() { proto.RegisterFile("colosseuma/query.proto", fileDescriptor_f7dad3c38e43f6de) }

var fileDescriptor_f7dad3c38e43f6de = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x3f, 0x6f, 0x13, 0x31,
	0x18, 0xc6, 0xe3, 0xb4, 0x64, 0x30, 0x82, 0xc1, 0x94, 0x7f, 0xa7, 0xe6, 0x0a, 0x16, 0x50, 0x1a,
	0x24, 0x9b, 0x94, 0x81, 0x81, 0x29, 0xad, 0x44, 0xd7, 0x72, 0x6c, 0x2c, 0xc8, 0x49, 0xac, 0x93,
	0xa5, 0xbb, 0x7b, 0xaf, 0xf1, 0x05, 0x11, 0x21, 0x16, 0x06, 0x66, 0x24, 0xbe, 0x00, 0xe2, 0x03,
	0xf0, 0x39, 0x3a, 0x56, 0x62, 0xe9, 0x84, 0x50, 0xc2, 0x07, 0x41, 0x67, 0xbb, 0x3a, 0x43, 0xee,
	0x1a, 0xe8, 0x76, 0xb2, 0x9f, 0xe7, 0x79, 0x7f, 0xaf, 0xdf, 0x37, 0xc1, 0x37, 0x46, 0x90, 0x80,
	0xd6, 0x72, 0x9a, 0x0a, 0x7e, 0x34, 0x95, 0x93, 0x19, 0xcb, 0x27, 0x50, 0x00, 0xb9, 0x5e, 0x9d,
	0xb3, 0xea, 0x33, 0xd8, 0x88, 0x21, 0x06, 0xa3, 0xe0, 0xe5, 0x97, 0x15, 0x07, 0x9b, 0x31, 0x40,
	0x9c, 0x48, 0x2e, 0x72, 0xc5, 0x45, 0x96, 0x41, 0x21, 0x0a, 0x05, 0x99, 0x76, 0xb7, 0xbd, 0x11,
	0xe8, 0x14, 0x34, 0x1f, 0x0a, 0x2d, 0x6d, 0x0d, 0xfe, 0xa6, 0x3f, 0x94, 0x85, 0xe8, 0xf3, 0x5c,
	0xc4, 0x2a, 0x33, 0x62, 0xa7, 0xbd, 0xe9, 0xe1, 0xe4, 0x62, 0x22, 0xd2, 0xb3, 0x90, 0x4d, 0xef,
	0x62, 0x04, 0x2a, 0x7b, 0xad, 0x67, 0xe9, 0x10, 0x12, 0x7b, 0x4b, 0x37, 0x30, 0x79, 0x51, 0x06,
	0x1f, 0x1a, 0x4b, 0x24, 0x8f, 0xa6, 0x52, 0x17, 0x34, 0xc2, 0xd7, 0xfe, 0x38, 0xd5, 0x39, 0x64,
	0x5a, 0x92, 0x67, 0xb8, 0x63, 0xa3, 0x6f, 0xa1, 0x3b, 0xe8, 0xe1, 0xe5, 0xdd, 0x2e, 0xab, 0xed,
	0x95, 0x59, 0xdb, 0xde, 0xfa, 0xf1, 0x8f, 0xad, 0x56, 0xe4, 0x2c, 0xf4, 0x11, 0xbe, 0x6d, 0x32,
	0x0f, 0x64, 0xb1, 0x0f, 0x2a, 0x7b, 0x69, 0x28, 0x5c, 0x41, 0x72, 0x15, 0xb7, 0xd5, 0xd8, 0xa4,
	0xae, 0x47, 0x6d, 0x35, 0xa6, 0x12, 0x07, 0x75, 0x62, 0xc7, 0x71, 0x80, 0x71, 0x75, 0xea, 0x58,
	0xee, 0x36, 0xb0, 0x54, 0x42, 0xc7, 0xe3, 0x59, 0xe9, 0xc8, 0x31, 0x0d, 0x92, 0x64, 0x99, 0xe9,
	0x39, 0xc6, 0xd5, 0x2b, 0xbb, 0x2a, 0x0f, 0x98, 0x1d, 0x09, 0x2b, 0x47, 0xc2, 0xec, 0xd8, 0xdd,
	0x48, 0xd8, 0xa1, 0x88, 0xa5, 0xf3, 0x46, 0x9e, 0x93, 0x7e, 0x43, 0xae, 0x99, 0xbf, 0xaa, 0x34,
	0x34, 0xb3, 0x76, 0xc1, 0x66, 0xca, 0x20, 0x8f, 0xb7, 0x6d, 0x78, 0xb7, 0x57, 0xf2, 0x5a, 0x0a,
	0x1f, 0x78, 0xf7, 0x74, 0x0d, 0x5f, 0x32, 0xc0, 0xe4, 0x23, 0xc2, 0x1d, 0x3b, 0x4c, 0xb2, 0xd3,
	0x80, 0xb4, 0xbc, 0x3d, 0x41, 0xef, 0x5f, 0xa4, 0xb6, 0x2e, 0xbd, 0xff, 0xe1, 0xfb, 0xaf, 0xcf,
	0xed, 0x2d, 0xd2, 0xe5, 0xfb, 0x67, 0xc2, 0x01, 0x5f, 0x5a, 0x65, 0xf2, 0x15, 0xf9, 0xaf, 0x44,
	0x1e, 0x9f, 0x57, 0xa1, 0x6e, 0xc1, 0x82, 0xfe, 0x7f, 0x38, 0x1c, 0x1a, 0x37, 0x68, 0x3b, 0x64,
	0xbb, 0x01, 0xcd, 0xfb, 0x31, 0xf1, 0x77, 0x6a, 0xfc, 0x9e, 0x7c, 0x41, 0xf8, 0x4a, 0x95, 0x33,
	0x48, 0x56, 0x70, 0xd6, 0x2d, 0xdd, 0xf9, 0x9c, 0xb5, 0x0b, 0x44, 0x7b, 0x86, 0xf3, 0x1e, 0xa1,
	0xab, 0x39, 0xf7, 0x9e, 0x1e, 0xcf, 0x43, 0x74, 0x32, 0x0f, 0xd1, 0xcf, 0x79, 0x88, 0x3e, 0x2d,
	0xc2, 0xd6, 0xc9, 0x22, 0x6c, 0x9d, 0x2e, 0xc2, 0xd6, 0xab, 0xae, 0x67, 0x7e, 0xeb, 0xdb, 0x8b,
	0x59, 0x2e, 0xf5, 0xb0, 0x63, 0xfe, 0x2e, 0x9e, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x79,
	0x33, 0x2b, 0xf6, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a CoinSymbol by id.
	CoinSymbol(ctx context.Context, in *QueryGetCoinSymbolRequest, opts ...grpc.CallOption) (*QueryGetCoinSymbolResponse, error)
	// Queries a list of CoinSymbol items.
	CoinSymbolAll(ctx context.Context, in *QueryAllCoinSymbolRequest, opts ...grpc.CallOption) (*QueryAllCoinSymbolResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/colosseuma.colosseuma.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CoinSymbol(ctx context.Context, in *QueryGetCoinSymbolRequest, opts ...grpc.CallOption) (*QueryGetCoinSymbolResponse, error) {
	out := new(QueryGetCoinSymbolResponse)
	err := c.cc.Invoke(ctx, "/colosseuma.colosseuma.Query/CoinSymbol", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CoinSymbolAll(ctx context.Context, in *QueryAllCoinSymbolRequest, opts ...grpc.CallOption) (*QueryAllCoinSymbolResponse, error) {
	out := new(QueryAllCoinSymbolResponse)
	err := c.cc.Invoke(ctx, "/colosseuma.colosseuma.Query/CoinSymbolAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a CoinSymbol by id.
	CoinSymbol(context.Context, *QueryGetCoinSymbolRequest) (*QueryGetCoinSymbolResponse, error)
	// Queries a list of CoinSymbol items.
	CoinSymbolAll(context.Context, *QueryAllCoinSymbolRequest) (*QueryAllCoinSymbolResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) CoinSymbol(ctx context.Context, req *QueryGetCoinSymbolRequest) (*QueryGetCoinSymbolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CoinSymbol not implemented")
}
func (*UnimplementedQueryServer) CoinSymbolAll(ctx context.Context, req *QueryAllCoinSymbolRequest) (*QueryAllCoinSymbolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CoinSymbolAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/colosseuma.colosseuma.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CoinSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCoinSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CoinSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/colosseuma.colosseuma.Query/CoinSymbol",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CoinSymbol(ctx, req.(*QueryGetCoinSymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CoinSymbolAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllCoinSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CoinSymbolAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/colosseuma.colosseuma.Query/CoinSymbolAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CoinSymbolAll(ctx, req.(*QueryAllCoinSymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "colosseuma.colosseuma.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "CoinSymbol",
			Handler:    _Query_CoinSymbol_Handler,
		},
		{
			MethodName: "CoinSymbolAll",
			Handler:    _Query_CoinSymbolAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "colosseuma/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetCoinSymbolRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCoinSymbolRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCoinSymbolRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCoinSymbolResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCoinSymbolResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCoinSymbolResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.CoinSymbol.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllCoinSymbolRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCoinSymbolRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCoinSymbolRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCoinSymbolResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCoinSymbolResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCoinSymbolResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.CoinSymbol) > 0 {
		for iNdEx := len(m.CoinSymbol) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CoinSymbol[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetCoinSymbolRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetCoinSymbolResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CoinSymbol.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllCoinSymbolRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCoinSymbolResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.CoinSymbol) > 0 {
		for _, e := range m.CoinSymbol {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCoinSymbolRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCoinSymbolRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCoinSymbolRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCoinSymbolResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCoinSymbolResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCoinSymbolResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinSymbol", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CoinSymbol.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCoinSymbolRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCoinSymbolRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCoinSymbolRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCoinSymbolResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCoinSymbolResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCoinSymbolResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinSymbol", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CoinSymbol = append(m.CoinSymbol, CoinSymbol{})
			if err := m.CoinSymbol[len(m.CoinSymbol)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
